server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/
  instance:
    hostname: peer2
#    prefer-ip-address: false

spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root