server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: peer1
#    prefer-ip-address: false

spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root