server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://root:root@peer1:8001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul

zuul:
  routes:
#    feign-client: /feign/**
#    user-routing:
#    用指定路径访问服务
    user-routing:
      serviceId: feign-client
      path: /feign/**
# 允许cookie等通过
#     sensitiveHeaders:
#  禁止所有服务名称访问
  ignored-services: "*"
# 前缀路径
  #  prefix: /api
  #  strip-prefix: true
# 过滤敏感路径
  ignored-patterns: /**/admin/**

hystrix:
  command:
    default:  # default默认全局配置，可以指定特定的服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# 设置全局的超时时间
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000
