server:
  port: 8102

spring:
  application:
    name: feign-service
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/test_baik_warehouse?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: bec123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    web:
      client:
        enabled: true
    # 采样比例默认0.1，为1表示全部上报
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://root:root@peer1:8001/eureka/
#      defaultZone: http://root:root@peer1:8001/eureka/,http://root:root@peer2:8002/eureka/  # 向两个注册中心注册
  instance:
    prefer-ip-address: true # 开启IP注册

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # mybatis驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印log信息

logging:
  level:
    org.springframework.cloud.sleuth: debug