#server:
#  port: 9100
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/zhmian/config.git
#          username: 1209320262@qq.com
#          password: 941010ay


spring:
  profiles:
    active: prod

---

spring:
  profiles: prod
  application:
    name: config-prod
server:
  port: 9001

---

spring:
  profiles: test
  application:
    name: config-test
server:
  port: 9002
