server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhmian/config.git
          username: 1209320262@qq.com
          password: 941010ay
  rabbitmq:
    host: 115.28.137.138
    port: 5672
    virtual-host: amqp
    username: guest
    password: guest
    connection-timeout: 10000
    template:
      mandatory: true
    addresses:
management:
  endpoints:
    web:
      exposure:
        include: "*"
