server:
  port: 8101
#  servlet:
#    context-path: /client

eureka:
  client:
    service-url:
      defaultZone: http://root:root@peer1:8001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: feign-client


# 开启feign支持hystrix的降级方法
feign:
  hystrix:
    enabled: true


# 设置全局的超时时间
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000


# 监控的管理
management:
  endpoint:
    health:
      show-details: always  # 监控端点显示详情
#  endpoints:
#    web:
#      exposure:
#        include: "*"

hystrix:
  command:
    default:  # default默认全局配置，可以指定特定的服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:   # 熔断是否开启（和降级不同）
          enabled: true
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 20000
#          sleepWindowInMilliseconds: 15000
#      circuitBreaker:
#        requestVolumeThreshold: 5
#        errorThresholdPercentage: 60
logging:
  level:
    org.springframework.cloud.sleuth: debug
#    com.tuling.api: debug # feign client 日志打印

#  logging.level.org.springframework.cloud.sleuth=debug