server:
  port: 8101
#  servlet:
#    context-path: /client

eureka:
  client:
    service-url:
      defaultZone: http://root:root@peer1:8001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: feign-client
  rabbitmq:
    host: 115.28.137.138
    port: 5672
    #    virtual-host: amqp
    username: guest
    password: guest
    connection-timeout: 10000
    template:
      mandatory: true


# 开启feign支持hystrix的降级方法
feign:
  hystrix:
    enabled: true


# 设置全局的超时时间
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000


# 监控的管理
management:
  endpoint:
    health:
      show-details: always  # 监控端点显示详情
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:  # default默认全局配置，可以指定特定的服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:   # 熔断是否开启（和降级不同）
          enabled: true
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 20000
#          sleepWindowInMilliseconds: 15000
#      circuitBreaker:
#        requestVolumeThreshold: 5
#        errorThresholdPercentage: 60
logging:
  level:
    org.springframework.cloud.sleuth: debug
#    com.tuling.api: debug # feign client 日志打印

#  logging.level.org.springframework.cloud.sleuth=debug



#    配置ribbon 负载均衡
#stu-provide:
#  ribbon:
#
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
#    ConnectTimeout: 500 #请求连接超时时间
#    ReadTimeout: 1000 #请求处理的超时时间
#    OkToRetryOnAllOperations: true #对所有请求都进行重试
#    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#    MaxAutoRetries: 1 #对当前实例的重试次数